In [100]:
import pandas as pd
import numpy as np

In [101]:
data = pd.read_csv("Pokemon.csv")

In [102]:
data

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [103]:
new_data = data.drop('Type 1', axis = 1)

In [104]:
labels = data['Type 1'].copy()

In [105]:
features = new_data

In [106]:
features

#                   Name  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Poison    318  45      49       49       65   
1      2                Ivysaur  Poison    405  60      62       63       80   
2      3               Venusaur  Poison    525  80      82       83      100   
3      3  VenusaurMega Venusaur  Poison    625  80     100      123      122   
4      4             Charmander     NaN    309  39      52       43       60   
..   ...                    ...     ...    ...  ..     ...      ...      ...   
795  719                Diancie   Fairy    600  50     100      150      100   
796  719    DiancieMega Diancie   Fairy    700  50     160      110      160   
797  720    HoopaHoopa Confined   Ghost    600  80     110       60      150   
798  720     HoopaHoopa Unbound    Dark    680  80     160       60      170   
799  721              Volcanion   Water    600  80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
0         65     45           1      False  
1         80     60           1      False  
2        100     80           1      False  
3        120     80           1      False  
4         50     65           1      False  
..       ...    ...         ...        ...  
795      150     50           6       True  
796      110    110           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True  

[800 rows x 12 columns]

In [107]:
labels

0        Grass
1        Grass
2        Grass
3        Grass
4         Fire
        ...   
795       Rock
796       Rock
797    Psychic
798    Psychic
799       Fire
Name: Type 1, Length: 800, dtype: object

In [213]:
np.unique(labels)

array([0., 1.], dtype=float32)

In [109]:
no_classes = 18

In [110]:
features.columns 

Index(['#', 'Name', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [111]:
#features = features.drop('#',axis = 1)
features = features.drop('Type 2',axis = 1)

In [112]:
features.columns 

Index(['#', 'Name', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def',
       'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [113]:
from sklearn.preprocessing import OneHotEncoder
#labels = labels.reshape(-1, 1)
features = OneHotEncoder().fit_transform(features).toarray() 


In [114]:
labels = labels.to_numpy()

In [115]:
labels

array(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
       'Fire', 'Water', 'Water', 'Water', 'Water', 'Bug', 'Bug', 'Bug',
       'Bug', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Normal', 'Normal',
       'Normal', 'Normal', 'Normal', 'Normal', 'Poison', 'Poison',
       'Electric', 'Electric', 'Ground', 'Ground', 'Poison', 'Poison',
       'Poison', 'Poison', 'Poison', 'Poison', 'Fairy', 'Fairy', 'Fire',
       'Fire', 'Normal', 'Normal', 'Poison', 'Poison', 'Grass', 'Grass',
       'Grass', 'Bug', 'Bug', 'Bug', 'Bug', 'Ground', 'Ground', 'Normal',
       'Normal', 'Water', 'Water', 'Fighting', 'Fighting', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Psychic', 'Psychic', 'Psychic',
       'Psychic', 'Fighting', 'Fighting', 'Fighting', 'Grass', 'Grass',
       'Grass', 'Water', 'Water', 'Rock', 'Rock', 'Rock', 'Fire', 'Fire',
       'Water', 'Water', 'Water', 'Electric', 'Electric', 'Normal',
       'Normal', 'Normal', 'Water', 'Water', 'Poison', 'Poison',

In [116]:
from sklearn.preprocessing import LabelEncoder 

encoder = LabelEncoder()

labels = encoder.fit_transform(labels)

In [117]:
labels 

array([ 9,  9,  9,  9,  6,  6,  6,  6,  6, 17, 17, 17, 17,  0,  0,  0,  0,
        0,  0,  0, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13,  3,  3, 10, 10,
       13, 13, 13, 13, 13, 13,  4,  4,  6,  6, 12, 12, 13, 13,  9,  9,  9,
        0,  0,  0,  0, 10, 10, 12, 12, 17, 17,  5,  5,  6,  6, 17, 17, 17,
       14, 14, 14, 14,  5,  5,  5,  9,  9,  9, 17, 17, 15, 15, 15,  6,  6,
       17, 17, 17,  3,  3, 12, 12, 12, 17, 17, 13, 13, 17, 17,  8,  8,  8,
        8, 15, 14, 14, 17, 17,  3,  3,  9,  9, 10, 10,  5,  5, 12, 13, 13,
       10, 10, 12,  9, 12, 12, 17, 17, 17, 17, 17, 17, 14,  0, 11,  3,  6,
        0,  0, 12, 17, 17, 17, 17, 12, 12, 17,  3,  6, 12, 15, 15, 15, 15,
       15, 15, 12, 11,  3,  6,  2,  2,  2, 14, 14, 14, 14,  9,  9,  9,  6,
        6,  6, 17, 17, 17, 12, 12, 12, 12,  0,  0,  0,  0, 13, 17, 17,  3,
        4, 12,  4,  4, 14, 14,  3,  3,  3,  3,  9, 17, 17, 15, 17,  9,  9,
        9, 12,  9,  9,  0, 17, 17, 14,  1,  1, 17,  8, 14, 14, 12,  0,  0,
       12, 10, 16, 16,  4

In [118]:
from sklearn.preprocessing import StandardScaler 
sc_X = StandardScaler()
features = sc_X.fit_transform(features)


In [214]:
from sklearn.linear_model import LogisticRegression

In [215]:
model = LogisticRegression(random_state=0)

In [216]:
model.fit(features,labels)

C:\Users\purvanya tyagi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


TypeError: __array__() takes 1 positional argument but 2 were given

In [122]:
'''import tensorflow as tf
n_nodes_hl1 = 500
n_nodes_hl2 = 500
n_nodes_hl3 = 500

n_classes = 10
batch_size = 100
features = tf.convert_to_tensor(features,dtype = tf.float64)
output_layer = {'weights':tf.Variable(tf.random_normal([500, 18])),
                'biases':tf.Variable(tf.random_normal([18])),}
l1 = tf.keras.layers.Dense(500 , activation = 'relu')(features)
l2 = tf.keras.layers.Dense(500 , activation = 'relu')(l1)
l3 = tf.keras.layers.Dense(500 , activation = 'relu')(l2)
output =  tf.keras.layers.Dense(18, activation = 'relu')(l3)'''

"import tensorflow as tf\nn_nodes_hl1 = 500\nn_nodes_hl2 = 500\nn_nodes_hl3 = 500\n\nn_classes = 10\nbatch_size = 100\nfeatures = tf.convert_to_tensor(features,dtype = tf.float64)\noutput_layer = {'weights':tf.Variable(tf.random_normal([500, 18])),\n                'biases':tf.Variable(tf.random_normal([18])),}\nl1 = tf.keras.layers.Dense(500 , activation = 'relu')(features)\nl2 = tf.keras.layers.Dense(500 , activation = 'relu')(l1)\nl3 = tf.keras.layers.Dense(500 , activation = 'relu')(l2)\noutput =  tf.keras.layers.Dense(18, activation = 'relu')(l3)"

In [123]:
from sklearn.tree import DecisionTreeClassifier

In [124]:
tree = DecisionTreeClassifier()

tree.fit(features,labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [125]:
from keras.models import Sequential
from keras.layers import Dense

In [179]:
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [217]:
model = Sequential()
model.add(Dense(500, input_shape=(features[0].shape), activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

TypeError: float() argument must be a string or a number, not 'Dimension'

In [196]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [198]:
model.fit(features, labels, epochs=20,batch_size = 10)

Epoch 1/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0063 - acc: 0.9982
Epoch 2/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0050 - acc: 0.9988
Epoch 3/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0013 - acc: 0.9997
Epoch 4/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0012 - acc: 0.9997
Epoch 5/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0025 - acc: 0.9992
Epoch 6/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0068 - acc: 0.9986
Epoch 7/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0095 - acc: 0.9984A: 1s - 
Epoch 8/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0093 - acc: 0.9979
Epoch 9/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0041 - acc: 0.9990A: 
Epoch 10/20
800/800 [==============================] - 5s 6ms/step - loss: 0.0052 - acc: 0.9988
Epoch 11/20
800/800 [=================

In [190]:
predictions = model.predict(features)

In [ ]:
800 * 11

In [ ]:
800 * 12

In [169]:
features[21].shape

(2342,)

In [ ]:
labels[21].shape


In [175]:
from keras.utils import to_categorical
labels = to_categorical(labels, 18)

In [176]:
labels.shape

(800, 18)

In [177]:
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [193]:
print(np.argmax(predictions[5]))

6


In [199]:
loss , acc = model.evaluate(features,labels)

800/800 [==============================] - 1s 2ms/step


In [200]:
loss

1.1410478055040586e-05

In [219]:
accuracy = acc 

In [220]:
accuracy

1.0

In [204]:
tree.predict(features)

array([ 9,  9,  9,  9,  6,  6,  6,  6,  6, 17, 17, 17, 17,  0,  0,  0,  0,
        0,  0,  0, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13,  3,  3, 10, 10,
       13, 13, 13, 13, 13, 13,  4,  4,  6,  6, 12, 12, 13, 13,  9,  9,  9,
        0,  0,  0,  0, 10, 10, 12, 12, 17, 17,  5,  5,  6,  6, 17, 17, 17,
       14, 14, 14, 14,  5,  5,  5,  9,  9,  9, 17, 17, 15, 15, 15,  6,  6,
       17, 17, 17,  3,  3, 12, 12, 12, 17, 17, 13, 13, 17, 17,  8,  8,  8,
        8, 15, 14, 14, 17, 17,  3,  3,  9,  9, 10, 10,  5,  5, 12, 13, 13,
       10, 10, 12,  9, 12, 12, 17, 17, 17, 17, 17, 17, 14,  0, 11,  3,  6,
        0,  0, 12, 17, 17, 17, 17, 12, 12, 17,  3,  6, 12, 15, 15, 15, 15,
       15, 15, 12, 11,  3,  6,  2,  2,  2, 14, 14, 14, 14,  9,  9,  9,  6,
        6,  6, 17, 17, 17, 12, 12, 12, 12,  0,  0,  0,  0, 13, 17, 17,  3,
        4, 12,  4,  4, 14, 14,  3,  3,  3,  3,  9, 17, 17, 15, 17,  9,  9,
        9, 12,  9,  9,  0, 17, 17, 14,  1,  1, 17,  8, 14, 14, 12,  0,  0,
       12, 10, 16, 16,  4

In [206]:
new = np.array()

58

In [208]:
import tensorflow as tf
def neural_network_model(features):
    n_nodes_hl1 = 500
    n_nodes_hl2 = 500
    n_nodes_hl3 = 500

    n_classes = 18
    batch_size = 10
    l1 = tf.keras.layers.Dense(n_nodes_hl1 , activation = 'relu')(features)
    l2 = tf.keras.layers.Dense(n_nodes_hl2 , activation = 'relu')(l1)
    l3 = tf.keras.layers.Dense(n_nodes_hl3 , activation = 'relu')(l2)
    output =  tf.keras.layers.Dense(18, activation = 'relu')(l3)



def train_neural_network(x):
    prediction = neural_network_model(x)
    # OLD VERSION:
    #cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
    # NEW:
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=labels) )
    optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    hm_epochs = 20
    with tf.Session() as sess:
        # OLD:
        #sess.run(tf.initialize_all_variables())
        # NEW:
        sess.run(tf.global_variables_initializer())

        for epoch in range(hm_epochs):


            epoch_loss = 0
            for _ in range(int(mnist.train.num_examples/batch_size)):
                epoch_x, epoch_y = mnist.train.next_batch(batch_size)
                _, c = sess.run([optimizer, cost], feed_dict={x: epoch_x, y: epoch_y})
                epoch_loss += c

            print('Epoch', epoch, 'completed out of',hm_epochs,'loss:',epoch_loss)

        correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))

        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        print('Accuracy:',accuracy.eval({x:mnist.test.images, y:mnist.test.labels}))

train_neural_network(features)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



ValueError: Both labels and logits must be provided.